--- drivers/media/video/Makefile	2013-06-24 02:50:48.000000000 -0600
+++ drivers/media/video/Makefile	2013-08-01 23:38:05.000000000 -0600
@@ -212,7 +212,9 @@
 
 obj-y	+= davinci/
 
+ifeq ($(CONFIG_MSM_CAMERA),y)
 obj-$(CONFIG_MSM_CAMERA) += msm/
+endif
 obj-$(CONFIG_FB_MSM_WRITEBACK_MSM_PANEL) += msm/wfd/
 obj-$(CONFIG_ARCH_OMAP)	+= omap/
 #obj-$(CONFIG_MSM_VIDC) += msm_vidc/
